services:
  frontend-angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/usr/src/app
    command: ng serve --host 0.0.0.0 --poll 2000
    stdin_open: true
    tty: true
    container_name: frontend-helpBot-landingPage